import os, sys

help_msg = """
Usage:
    python generate_manual_yara_rule.py start_index

"""

try:
    with open('feature_manual_keywords.yar', 'w') as fh:
        fh.write('''
/*
common manual keywords, generated by python script
*/
        ''')
        with open('manual_keywords.ini', 'r') as fh2:
            index = int(sys.argv[1])
            for line in fh2.readlines():
                keyword = line.strip()
                fh.write('\n')
                fh.write('rule manual_keyword_{}\n'.format(keyword))
                fh.write('{\n')
                fh.write('    meta:\n')
                fh.write('        index = {}\n'.format(index))
                fh.write('    strings:\n')
                fh.write('        $a = "{}" nocase\n'.format(keyword))
                fh.write('    condition:\n')
                fh.write('        $a\n')
                fh.write('}\n')
                index += 1
except Exception,e:
    print(e)
    print(help_msg)
